name: Build and Release Anime List

on:
  schedule:
    # Runs daily at 08:00 UTC. You can adjust the time as needed.
    - cron: '0 8 * * *'
  workflow_dispatch: # Allows manual triggering from the Actions tab

permissions:
  contents: write # Required to create releases and commit

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run script to generate JSON
        run: python main.py

      - name: Check if file was generated
        id: check_file
        run: |
          if [ -f anime_tvdb_ids.json ]; then
            echo "file_exists=true" >> $GITHUB_OUTPUT
          else
            echo "file_exists=false" >> $GITHUB_OUTPUT
            echo "JSON file not found. Exiting."
            exit 1
          fi

      - name: Commit and push if changed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Configure git for the bot
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Stage the generated file
          git add anime_tvdb_ids.json
          
          # Commit and push if there are any changes
          if ! git diff --staged --quiet; then
            git commit -m "Update anime list for $(date -u +'%Y-%m-%d')"
            git push
          else
            echo "No changes to commit. The anime list is up-to-date."
          fi